name = "elementaryChemistry"
uuid = "95ad8c96-4a8b-47ff-b6a3-cf0853d8b4d4"
version = "0.1.0"

[compat]
julia = "1" 

[extras]
authors = ["baobabfruit88@gmail.com <baobabfruit88@gmail.com>"]
keywords = ["Chemistry julia"]
license = "MIT"